<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonDaftar</name>
   <tag></tag>
   <elementGuidId>05ad9ef5-668d-434b-b711-1d01bafb4196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href*='/register']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
