<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonMasuk</name>
   <tag></tag>
   <elementGuidId>3673509d-4eaf-42bd-ab60-5577e9cb2dd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href*='login']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
