<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelTextErrorInvalidPassword</name>
   <tag></tag>
   <elementGuidId>ef9365fa-845c-4744-ac7f-fce8afcae86d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[class*='invalid-feedback']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
