<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonDaftarSekarang</name>
   <tag></tag>
   <elementGuidId>ce26517f-fd0e-425a-b698-dd3f15c2f9ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[data-testid*='submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
